name: iphone_14__15_pro___1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  dotted_border: ^2.1.0
  kommunicate_flutter: ^1.6.4
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanCondensedRegular.ttf
          weight: 400
    - family: Rhodium Libre
      fonts: 
        - asset: assets/fonts/RhodiumLibreRegular.ttf
          weight: 400
